# Generated by Django 4.0 on 2021-12-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codProd', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('pice', models.FloatField(default=0)),
                ('theAmount', models.IntegerField(default=0)),
                ('manufacturer', models.IntegerField(default=0)),
                ('shed', models.IntegerField(default=0)),
            ],
        ),
    ]
