# Generated by Django 4.0 on 2021-12-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_Nome', models.CharField(max_length=200)),
                ('prod_Codigo', models.IntegerField(default=0)),
                ('prod_Preco', models.FloatField(default=0)),
                ('prod_Total_estoque', models.IntegerField(default=0)),
                ('prod_Fornecedor', models.IntegerField(default=0)),
            ],
        ),
    ]
