# Generated by Django 4.0 on 2021-12-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venda_Cod', models.IntegerField(default=0)),
                ('venda_Data', models.DateTimeField(default='00/00/0000 00:00:00')),
                ('venda_Cliente', models.IntegerField(default=0)),
                ('venda_Prod', models.IntegerField(default=0)),
                ('venda_Metodo_Pagamento', models.IntegerField(default=0)),
                ('venda_estado_destino', models.CharField(max_length=10)),
                ('venda_cliente', models.IntegerField(default=0)),
            ],
        ),
    ]
