# Generated by Django 4.0 on 2021-12-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='venda_quantidade_produto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendas',
            name='venda_total',
            field=models.FloatField(default=0.0),
        ),
    ]
