# Generated by Django 4.0 on 2021-12-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_vendas_venda_quantidade_produto_vendas_venda_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='venda_cliente',
        ),
    ]
