# Generated by Django 4.0 on 2021-12-25 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='ChoiceModificado',
        ),
    ]
