# Generated by Django 4.0 on 2021-12-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_choice_choicemodificado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChoiceModificado',
            new_name='Choice',
        ),
    ]
